apiVersion: apps/v1
kind: Deployment
metadata:
  name: jsonnet-dev
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: jsonnet-dev
  template:
    metadata:
      labels:
        app.kubernetes.io/name: jsonnet-dev
    spec:
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default (printf "v%s" .Chart.AppVersion) }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          envFrom:
            - secretRef:
                name: jsonnet-dev-postgres
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 60
          readinessProbe:
            httpGet:
              path: /
              port: http
          ports:
            - containerPort: 8000
              name: http
              protocol: TCP
            - containerPort: 8080
              name: http-metrics
              protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 200m
              memory: 200Mi
