apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jsonnet-dev
  annotations:
    cert-manager.io/cluster-issuer: main
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: jsonnet.dev
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: jsonnet-dev
                port:
                  name: http
  tls:
    - hosts:
        - jsonnet.dev
      secretName: jsonnet-playground-tls
