apiVersion: v1
kind: Service
metadata:
  name: jsonnet-dev
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: jsonnet-dev
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
