replicaCount: 1

image:
  repository: ghcr.io/rgst-io/jsonnet-playground
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

# OVERRIDE ME.
databaseURL: ""

# See: https://artifacthub.io/packages/helm/groundhog2k/postgres
postgres:
  enabled: true
  image:
    tag: "14.6"
  imagePullPolicy: IfNotPresent
  storage:
    requestedSize: 10Gi
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
