apiVersion: v1
kind: Service
metadata:
  name: komga
  namespace: media-center
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: komga
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
