---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: komga-data
  namespace: media-center

spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: komga-config
  namespace: media-center

spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
