apiVersion: apps/v1
kind: Deployment
metadata:
  name: komga
  namespace: media-center
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: komga
  template:
    metadata:
      labels:
        app.kubernetes.io/name: komga
    spec:
      securityContext:
        supplementalGroups:
          - 1000
        fsGroup: 1000
      initContainers:
        - name: chown
          image: alpine
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: config
              mountPath: /data/config
            - name: data
              mountPath: /data/media
          command:
            - sh
            - -c
            - (chmod 0775 /data/*; chgrp 1000 /data/*; exit 0)
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: komga-config
        - name: data
          persistentVolumeClaim:
            claimName: komga-data
      containers:
        - name: komga
          image: gotson/komga
          imagePullPolicy: Always
          env:
            - name: TZ
              value: America/Los_Angeles
            - name: PUID
              value: "999"
            - name: PGID
              value: "999"
            - name: NVIDIA_VISIBLE_DEVICES
              value: "all"
            - name: VERSION
              value: "docker"
          # livenessProbe:
          #   httpGet:
          #     path: /identity
          #     port: plex-http
          #   initialDelaySeconds: 60
          # readinessProbe:
          #   httpGet:
          #     path: /identity
          #     port: plex-http
          ports:
            - containerPort: 8080
              name: http
          volumeMounts:
            - name: config
              mountPath: /config
            - name: data
              mountPath: /data
          resources:
            requests:
              cpu: "500m"
              memory: 500Mi
            limits:
              cpu: "1"
              memory: 1Gi
